model_list:
  - model_name: my-langfuse-model
    litellm_params:
      model: langfuse/openai-model
      api_key: os.environ/OPENAI_API_KEY
  - model_name: openai/*
    litellm_params:
      model: openai/*
      api_key: os.environ/OPENAI_API_KEY